source 'https://github.com/CocoaPods/Specs.git'

platform:ios,'8.0'
use_frameworks!

target "GesturePassword" do
    pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'Swift3'
end

target "GesturePasswordTests" do
end
