source 'https://github.com/CocoaPods/Specs.git'

platform:ios,'8.0'
use_frameworks!

target "GesturePassword" do
    #pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'Swift3'
end

target "GesturePasswordTests" do
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '2.3'
        end
    end
end
